### PR TITLE
add carthage support

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by AndrewSB** [comment]
hey @thii, I saw you reverted this merge, what happened?

**Comment by thii** [comment]
@AndrewSB Sorry for not checking it carefully before merging. Because you deleted the original scheme, all the tests failed.

**Comment by AndrewSB** [comment]
Ahh, I'm sorry about that. I'm going to create a new pull request, I'll make sure the tests are passing (would love your input if they're not)

**Comment by AndrewSB** [comment]
working on this in #21

**Pull request merged**
